Q1. create a program of finding total number of upper letters,lower letters ,digits and the symbols using for loop,strings and a if elif and else

In [7]:
#1 Program

string = input("Enter a String: ")

upper_count, lower_count, digit_count, symbol_count, whitespaces_count = 0, 0, 0, 0, 0

for char in string:
  if char.isupper():
    upper_count += 1
  elif char.islower():
    lower_count += 1
  elif char.isdigit():
    digit_count += 1
  elif char.isspace():
    whitespaces_count += 1
  else:
    symbol_count += 1

print("Uppercase ", upper_count)
print("Lowercase ", lower_count)
print("Digits ", digit_count)
print("Symbols ", symbol_count)
print("Whitespaces ", whitespaces_count)

Enter a String: Hello, Saurabh!!! 12345
Uppercase  2
Lowercase  10
Digits  5
Symbols  4
Whitespaces  2

Q2. Manav wants to know all the possible dates of February 2024. To help Manav write a prgram that can
take month and year as input and can print all the possible dates of that month in given format :
dd/mm/yyyy

In [8]:
#2 Program

month = int(input("Enter month: "))
year = int(input("Enter year: "))

days_in_month = [31,28,31,30,31,30,31,31,30,31,30,31]

if(year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
  days_in_month[1] = 29

print("Possible dates are: ")
for day in range(1, days_in_month[month - 1] + 1):
  print(f"{day}/{month}/{year}")

Enter month: 3
Enter year: 2024
Possible dates are:
1/3/2024
2/3/2024
3/3/2024
4/3/2024
5/3/2024
6/3/2024
7/3/2024
8/3/2024
9/3/2024
10/3/2024
11/3/2024
12/3/2024
13/3/2024
14/3/2024
15/3/2024
16/3/2024
17/3/2024
18/3/2024
19/3/2024
20/3/2024
21/3/2024
22/3/2024
23/3/2024
24/3/2024
25/3/2024
26/3/2024
27/3/2024
28/3/2024
29/3/2024
30/3/2024
31/3/2024

Q3. Fibonacci series.

In [17]:
#3

num_terms = int(input("Enter the number of terms: "))

a, b = 0, 1

if num_terms <= 0:
    print("Please enter a positive integer.")
elif num_terms == 1:
    print("Fibonacci sequence up to", num_terms, ":")
    print(a)
else:
    print("Fibonacci sequence:")
    count = 0
    while count < num_terms:
        print(a)
        nth = a + b
        # Update values
        a = b
        b = nth
        count += 1

Enter the number of terms: 15
Fibonacci sequence:
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377